builds:
- env:
  - CGO_ENABLED=0
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
snapshot:
  name_template: 'SNAPSHOT-{{.Commit}}'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^tests:'
dockers:
  -
    binary: go-http-status
    image: jkernech/http-status
    tag_templates:
    - "{{ .Tag }}"
    - latest
